Remove some lambda expressions
These are causing NoSuchMethodError on application startup
(see https://bugs.openjdk.java.net/browse/JDK-8161588 for more details)
which can have a small impact on startup performance